#! /bin/sh

$HOME/.config/polybar/launch.sh &
picom &
feh --bg-fill ~/Wallpaper/XLuT4KzuIj0.jpg
bspc monitor -d 1 2 3 4 5 

# Global Settings
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config click_to_focus true

bspc config border_width         1
bspc config window_gap           0 
# bspc config top_padding         12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color Scheme
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#353b45"
bspc config borderless_monocle true
bspc config borderless_floating true

# Global Settings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer false
# Gaps
bspc config gapless_monocle false

# Window Rules
bspc rule -a Zathura state=tiled
